Resources:
  # Application Load Balancer 생성
  MyALB:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "my-alb"
      Subnets:
        - subnet-096199500134ce24d
        - subnet-0f43837d8284a3b54
      SecurityGroups:
        - sg-0926354644913ad25
      Scheme: "internet-facing"
      Tags:
        - Key: "Name"
          Value: "my-alb"

  # 타겟 그룹 생성
  MyTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "my-target-group"
      TargetType: "instance"
      VpcId: "vpc-0c8727fa4c5b3e932"
      HealthCheckProtocol: "HTTP"
      HealthCheckPath: "/health"
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthCheckHealthyThresholdCount: 5
      HealthCheckUnhealthyThresholdCount: 2
      
  # EC2 인스턴스 생성 (필요시)
  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t3.micro"
      ImageId: "ami-00e428798e77d38d9"  
      KeyName: "a081117-keypair.pem" 
      SubnetId: "subnet-0216b28c081a09688" 
      SecurityGroupIds:
        - sg-0e5b82180d4d0977e
      Tags:
        - Key: "Name"
          Value: "my-instance"

  # ALB 리스너 설정
  MyListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      LoadBalancerArn: !Ref MyALB
      Port: 80 
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref MyTargetGroup
